// Audits every theme and generates Shared/Theme/ThemeCatalog.swift.
// Usage: node design/themes/build.js   (exits non-zero if any theme fails)
const fs = require('fs');
const path = require('path');
const THEMES = require('./themes.js');

const rgb = h => { const n = parseInt(h.slice(1), 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255]; };
const hex = c => '#' + c.map(v => Math.round(v).toString(16).padStart(2, '0')).join('').toUpperCase();
const mix = (a, b, t) => hex(rgb(a).map((v, i) => v * (1 - t) + rgb(b)[i] * t));
const lum = h => {
  const c = rgb(h).map(v => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); });
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
};
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p); return (x + 0.05) / (y + 0.05); };

let failures = [];
let report = '# Theme audit\n\nGenerated by `node design/themes/build.js`. Text needs 4.5:1. The counting numeral is very large and switches ink where the fill crosses it, so it needs 3:1 against the filled part and against the unfilled part, each with its own ink.\n\n';
report += '| Theme | Text | Secondary on bg | Secondary on surface | Action as text | Label on action | Worst numeral on stage |\n|---|---:|---:|---:|---:|---:|---:|\n';

const derived = {};
for (const t of THEMES) {
  const checks = [
    ['text', ratio(t.text, t.bg), 4.5],
    ['text2/bg', ratio(t.text2, t.bg), 4.5],
    ['text2/surface', ratio(t.text2, t.surface), 4.5],
    ['action/bg', ratio(t.action, t.bg), 4.5],
    ['onAction', ratio(t.onAction, t.action), 4.5],
  ];
  // Stage: the unfilled part is the tally color pulled toward the background.
  const inks = [t.text, t.bg, '#FFFFFF', '#141414'];
  // The numeral switches ink where the fill crosses it, so each region picks its own best ink.
  const best = bg => inks.map(ink => ({ ink, r: ratio(ink, bg) })).sort((a, b) => b.r - a.r)[0];
  const stage = t.tallies.map(c => {
    const base = mix(c, t.bg, t.scheme === 'dark' ? 0.62 : 0.5);
    const onFill = best(c), onBase = best(base);
    return { color: c, base, on: onFill.ink, onBase: onBase.ink, worst: Math.min(onFill.r, onBase.r) };
  });
  const worstStage = Math.min(...stage.map(s => s.worst));
  checks.push(['stage', worstStage, 3.0]);
  const bad = checks.filter(([, v, min]) => v < min);
  bad.forEach(([k, v, min]) => failures.push(`${t.name}: ${k} ${v.toFixed(2)} < ${min}`));
  const f = (v, min) => (v < min ? `**${v.toFixed(2)} ✗**` : v.toFixed(2));
  report += `| ${t.name} | ${f(checks[0][1], 4.5)} | ${f(checks[1][1], 4.5)} | ${f(checks[2][1], 4.5)} | ${f(checks[3][1], 4.5)} | ${f(checks[4][1], 4.5)} | ${f(worstStage, 3)} |\n`;
  derived[t.id] = stage;
}
report += failures.length ? `\n${failures.length} failures:\n\n${failures.map(f => '- ' + f).join('\n')}\n` : '\nEvery theme passes.\n';
fs.writeFileSync(path.join(__dirname, 'AUDIT.md'), report);

// ── Swift ──
const sx = h => '0x' + h.slice(1).toUpperCase();
const q = s => JSON.stringify(s);
let swift = `// Generated by design/themes/build.js from design/themes/themes.js. Do not edit by hand.
import Foundation

extension TallyTheme {
    static let all: [TallyTheme] = [
`;
for (const t of THEMES) {
  const st = derived[t.id];
  swift += `        TallyTheme(
            id: ${q(t.id)}, name: ${q(t.name)}, kind: .${t.kind}, scheme: .${t.scheme},
            numeral: .${t.numeral}, particles: .${t.particles}, stage: .${t.stage},
            mood: ${q(t.mood)}, signature: ${t.signature ? q(t.signature) : 'nil'},
            background: ${sx(t.bg)}, surface: ${sx(t.surface)}, raised: ${sx(t.raised)}, divider: ${sx(t.divider)},
            text: ${sx(t.text)}, text2: ${sx(t.text2)}, action: ${sx(t.action)}, onAction: ${sx(t.onAction)},
            tallies: [${st.map(s => sx(s.color)).join(', ')}],
            talliesBase: [${st.map(s => sx(s.base)).join(', ')}],
            talliesOn: [${st.map(s => sx(s.on)).join(', ')}],
            talliesOnBase: [${st.map(s => sx(s.onBase)).join(', ')}]
        ),
`;
}
swift += `    ]
}
`;
const target = path.join(__dirname, '..', '..', 'Shared', 'Theme', 'ThemeCatalog.swift');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, swift);

// JSON copy for the mockups
fs.writeFileSync(path.join(__dirname, 'themes.json'), JSON.stringify(THEMES.map(t => ({ ...t, stage: t.stage, derived: derived[t.id] })), null, 1));

console.log(report);
if (failures.length) process.exit(1);
