// Audits every theme and generates Shared/Theme/ThemeCatalog.swift.
// Usage: node design/themes/build.js   (exits non-zero if any theme fails)
const fs = require('fs');
const path = require('path');
const THEMES = require('./themes.js');

const rgb = h => { const n = parseInt(h.slice(1), 16); return [(n >> 16) & 255, (n >> 8) & 255, n & 255]; };
const hex = c => '#' + c.map(v => Math.round(v).toString(16).padStart(2, '0')).join('').toUpperCase();
const mix = (a, b, t) => hex(rgb(a).map((v, i) => v * (1 - t) + rgb(b)[i] * t));
const lum = h => {
  const c = rgb(h).map(v => { v /= 255; return v <= 0.03928 ? v / 12.92 : Math.pow((v + 0.055) / 1.055, 2.4); });
  return 0.2126 * c[0] + 0.7152 * c[1] + 0.0722 * c[2];
};
const ratio = (a, b) => { const [x, y] = [lum(a), lum(b)].sort((p, q) => q - p); return (x + 0.05) / (y + 0.05); };

// ── HSL helpers for deriving each theme's other appearance ──
const toHsl = h => {
  const [r, g, b] = rgb(h).map(v => v / 255);
  const max = Math.max(r, g, b), min = Math.min(r, g, b), l = (max + min) / 2;
  if (max === min) return [0, 0, l];
  const d = max - min, s = l > 0.5 ? d / (2 - max - min) : d / (max + min);
  let hue = max === r ? (g - b) / d + (g < b ? 6 : 0) : max === g ? (b - r) / d + 2 : (r - g) / d + 4;
  return [hue * 60, s, l];
};
const fromHsl = (hDeg, s, l) => {
  const k = n => (n + hDeg / 30) % 12, a = s * Math.min(l, 1 - l);
  const f = n => l - a * Math.max(-1, Math.min(k(n) - 3, Math.min(9 - k(n), 1)));
  return hex([f(0) * 255, f(8) * 255, f(4) * 255]);
};
const clamp = (v, lo, hi) => Math.max(lo, Math.min(hi, v));
// Moves a color's lightness step by step until it reaches `min` contrast against `bg`.
const pushTo = (color, bg, min, dir) => {
  let [h, s, l] = toHsl(color);
  let out = color;
  for (let i = 0; i < 100 && ratio(out, bg) < min; i++) { l = clamp(l + dir * 0.01, 0, 1); out = fromHsl(h, s, l); }
  return out;
};
const bestLabel = bg => ['#FFFFFF', '#141414'].map(ink => ({ ink, r: ratio(ink, bg) })).sort((a, b) => b.r - a.r)[0];

/// The other appearance of a theme: same hues and personality, lightness flipped.
/// Dark versions of light themes also dim the tally colors a little so a full-screen stage isn't glaring at night.
function deriveVariant(t) {
  const [bh, bs] = toHsl(t.bg);
  const [th, ts] = toHsl(t.text);
  const v = { ...t, scheme: t.scheme === 'light' ? 'dark' : 'light', derived: true };
  if (v.scheme === 'dark') {
    const sat = clamp(bs * 0.55, 0.04, 0.32);
    v.bg = fromHsl(bh, sat, 0.095);
    v.surface = fromHsl(bh, sat, 0.135);
    v.raised = fromHsl(bh, sat, 0.175);
    v.divider = fromHsl(bh, sat, 0.25);
    v.text = fromHsl(th, clamp(ts, 0, 0.25), 0.94);
    v.text2 = pushTo(fromHsl(th, clamp(ts, 0, 0.18), 0.7), v.surface, 4.6, +1);
    v.tallies = t.tallies.map(c => { const [h, s, l] = toHsl(c); return fromHsl(h, s * 0.9, l * 0.88); });
    let action = pushTo(t.action, v.bg, 4.8, +1);
    v.action = action;
  } else {
    const sat = clamp(bs * 0.6, 0.06, 0.4);
    v.bg = fromHsl(bh, sat, 0.955);
    v.surface = fromHsl(bh, sat, 0.985);
    v.raised = fromHsl(bh, sat, 0.915);
    v.divider = fromHsl(bh, sat, 0.85);
    v.text = fromHsl(th, clamp(ts * 1.2, 0.15, 0.45), 0.13);
    v.text2 = pushTo(fromHsl(th, clamp(ts, 0.1, 0.3), 0.38), v.raised, 4.6, -1);
    v.tallies = [...t.tallies];
    v.action = pushTo(t.action, v.bg, 4.8, -1);
  }
  // A tally color that nearly matches the new background (Swiss black, a white stripe) flips to stay visible.
  v.tallies = v.tallies.map(c => {
    const [h, s, l] = toHsl(c);
    if (v.scheme === 'dark' ? l > 0.15 : l < 0.9) return c;
    return v.scheme === 'dark' ? fromHsl(h, s, 0.8) : fromHsl(th, clamp(ts, 0.2, 0.4), 0.32);
  });
  const label = bestLabel(v.action);
  v.onAction = label.ink;
  // If neither label passes, keep moving the action color away from its label.
  if (label.r < 4.5) {
    v.action = pushTo(v.action, label.ink, 4.6, label.ink === '#FFFFFF' ? -1 : +1);
    v.onAction = bestLabel(v.action).ink;
  }
  return v;
}

const VARIANTS = THEMES.map(deriveVariant);
const ALL = [...THEMES, ...VARIANTS];

let failures = [];
let report = '# Theme audit\n\nGenerated by `node design/themes/build.js`. Text needs 4.5:1. The counting numeral is very large and switches ink where the fill crosses it, so it needs 3:1 against the filled part and against the unfilled part, each with its own ink.\n\n';
report += '| Theme | Text | Secondary on bg | Secondary on surface | Action as text | Label on action | Worst numeral on stage |\n|---|---:|---:|---:|---:|---:|---:|\n';

const derived = {};
for (const t of ALL) {
  const checks = [
    ['text', ratio(t.text, t.bg), 4.5],
    ['text2/bg', ratio(t.text2, t.bg), 4.5],
    ['text2/surface', ratio(t.text2, t.surface), 4.5],
    ['action/bg', ratio(t.action, t.bg), 4.5],
    ['onAction', ratio(t.onAction, t.action), 4.5],
  ];
  // Stage: the unfilled part is the tally color pulled toward the background.
  const inks = [t.text, t.bg, '#FFFFFF', '#141414'];
  // The numeral switches ink where the fill crosses it, so each region picks its own best ink.
  const best = bg => inks.map(ink => ({ ink, r: ratio(ink, bg) })).sort((a, b) => b.r - a.r)[0];
  const stage = t.tallies.map(c => {
    const base = mix(c, t.bg, t.scheme === 'dark' ? 0.62 : 0.5);
    const onFill = best(c), onBase = best(base);
    return { color: c, base, on: onFill.ink, onBase: onBase.ink, worst: Math.min(onFill.r, onBase.r) };
  });
  const worstStage = Math.min(...stage.map(s => s.worst));
  checks.push(['stage', worstStage, 3.0]);
  const bad = checks.filter(([, v, min]) => v < min);
  bad.forEach(([k, v, min]) => failures.push(`${t.name} ${t.scheme}: ${k} ${v.toFixed(2)} < ${min}`));
  const f = (v, min) => (v < min ? `**${v.toFixed(2)} ✗**` : v.toFixed(2));
  report += `| ${t.name} (${t.scheme}${t.derived ? ', derived' : ''}) | ${f(checks[0][1], 4.5)} | ${f(checks[1][1], 4.5)} | ${f(checks[2][1], 4.5)} | ${f(checks[3][1], 4.5)} | ${f(checks[4][1], 4.5)} | ${f(worstStage, 3)} |\n`;
  derived[t.id + ':' + t.scheme] = stage;
}
report += failures.length ? `\n${failures.length} failures:\n\n${failures.map(f => '- ' + f).join('\n')}\n` : '\nEvery theme passes.\n';
fs.writeFileSync(path.join(__dirname, 'AUDIT.md'), report);

// ── Swift ──
const sx = h => '0x' + h.slice(1).toUpperCase();
const q = s => JSON.stringify(s);
let swift = `// Generated by design/themes/build.js from design/themes/themes.js. Do not edit by hand.
import Foundation

extension TallyTheme {
    static let all: [TallyTheme] = [
`;
const emit = t => {
  const st = derived[t.id + ':' + t.scheme];
  return `        TallyTheme(
            id: ${q(t.id)}, name: ${q(t.name)}, kind: .${t.kind}, scheme: .${t.scheme},
            numeral: .${t.numeral}, particles: .${t.particles}, stage: .${t.stage},
            mood: ${q(t.mood)}, signature: ${t.signature ? q(t.signature) : 'nil'},
            background: ${sx(t.bg)}, surface: ${sx(t.surface)}, raised: ${sx(t.raised)}, divider: ${sx(t.divider)},
            text: ${sx(t.text)}, text2: ${sx(t.text2)}, action: ${sx(t.action)}, onAction: ${sx(t.onAction)},
            tallies: [${st.map(s => sx(s.color)).join(', ')}],
            talliesBase: [${st.map(s => sx(s.base)).join(', ')}],
            talliesOn: [${st.map(s => sx(s.on)).join(', ')}],
            talliesOnBase: [${st.map(s => sx(s.onBase)).join(', ')}]
        ),
`;
};
for (const t of THEMES) swift += emit(t);
swift += `    ]

    /// Each theme's other appearance (derived: same hues, lightness flipped).
    static let alternates: [TallyTheme] = [
`;
for (const t of VARIANTS) swift += emit(t);
swift += `    ]
}
`;
const target = path.join(__dirname, '..', '..', 'Shared', 'Theme', 'ThemeCatalog.swift');
fs.mkdirSync(path.dirname(target), { recursive: true });
fs.writeFileSync(target, swift);

// JSON copy for the mockups
fs.writeFileSync(path.join(__dirname, 'themes.json'), JSON.stringify(ALL.map(t => ({ ...t, stage: t.stage, derived: derived[t.id + ':' + t.scheme] })), null, 1));

console.log(report);
if (failures.length) process.exit(1);
